[package]

name = "freira-db"
version = "0.0.1"
authors = [ "Mateus Freira <mateus.freira@gmail.com>" ]

[dependencies]
tokio = "0.1.13"
futures = "0.1.25"
ws = "*"
env_logger = "*"
rustc-serialize = "*"
bincode = "*"
serde = "*"
timer = "*"
chrono = "*"
thread-id = "*"

