name: Docker Image CI
on: 
    push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nun-db:latest
    - name: Re-tag
      run: docker tag freira-db:latest nun-db:$(date +%s)      
